### PR TITLE
Fix: onSelect usage inside useCallback included in dependency array

### PR DESCRIPTION
**Pull request by fabiosenracorrea**
## Problem

`onSelect` prop callback was not being included in the dependency array on the `useCallback` calls inside `Node Element` and `Leaf Element`.

## Implication

This leads to inconsistencies if any state is referenced inside that callback, as its 'version' would be out of sync with the actual call.

## Solution

Simply added it to the dependency array.

## Further observation:

While fixing this (and using the lib), i've realized any `setState` action used inside the `onSelect` callback triggers a 'bad state change' warning from React. That happens because of `onSelect` calls inside setStates on our main component. This can be avoided by using a `setTimeout(() => setState(x), 0)` call inside the `onSelect` callback, so it's not breaking as the dependency issue, but would be a nice fix. Since it could change the structure of the 'genericSetStater' logic and usage, i initially opted to point this out before further modifying the code.

### CODE REVIEW

**Comment by ortonomy** [comment]
Thanks for the feedback and the contributing with a PR! It's been a while since I wrote this -- (can you point out at lines where the you think further fixes should be applied?)

I'll review this weekend and merge if appropriate

**Comment by kanerogers** [comment]
Hey @ortonomy! Thanks so much for the awesome library - I've just ran into the issue that @fabiosenracorrea has described here. Have you had a chance to review this fix?

**Comment by ortonomy** [comment]
@kanerogers  @fabiosenracorrea -- thanks for contribution. I have merged this request, but I haven't had a chance to set up CI/CD for this to automatically make a release to NPM, so you'll have to wait until I get a chance. 

RE: `further observations` @fabiosenracorrea -- can you open an issue for this so that we can track it and address it and devise a solution. the `setTimeout` approach seems dirty.

**Comment by ortonomy** [comment]
@kanerogers @fabiosenracorrea -- I've published a new version with the changes.

**Comment by kanerogers** [comment]
Thanks so much!

**Pull request merged**
